[[hedgedoc]]
url = "https://notes.cc24.dev/aDYS5CksT7iph_tQe0o2Eg"

[[hedgedoc]]
url = "https://notes.cc24.dev/p8ECX5-DRrerhVnSJ6yTvA"

[server]
data_dir = "/home/user01/Projekte/hashcards/.hashcards"
