name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      # The version of the new release.
      version: ${{ steps.parse.outputs.version }}
      # The changelog text for the new release.
      changelog: ${{ steps.parse.outputs.changelog }}
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: parse CHANGELOG.xml
        id: parse
        run: |
          python release.py >> $GITHUB_OUTPUT
          echo "Parsed version and changelog:"
          cat $GITHUB_OUTPUT

      - name: Check if tag exists
        run: |
          if git rev-parse "v${{ steps.parse.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.parse.outputs.version }} already exists!"
            exit 1
          fi

      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.parse.outputs.version }}" \
            --title "v${{ steps.parse.outputs.version }}" \
            --notes "${{ steps.parse.outputs.changelog }}" \
            --draft
