name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      # The version of the new release.
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: parse release version from CHANGELOG.xml
        run: |
          VERSION=$(python release.py --version-only)
          echo "Found version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: parse release notes from CHANGELOG.xml
        run: |
          python release.py --output release-notes.md

      - name: check if tag exists
        run: |
          if git rev-parse "v${{ steps.parse.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.parse.outputs.version }} already exists!"
            exit 1
          fi

      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.parse.outputs.version }}" \
            --title "v${{ steps.parse.outputs.version }}" \
            --notes-file release-notes.md \
            --draft
